import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import { Header } from '../components/header'
import { Footer } from '../components/footer'
import { Grid, TextField, Card, CardContent, Button } from '@mui/material'

export default function Contact() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className={styles.contact}>
        <Card>
          <CardContent>
            <form>
              <Grid container spacing={1}>
                <Grid xs={12} sm={6} item>
                  <TextField label="Prénom" placeholder="Entrez votre prénom" variant="outlined" fullWidth />
                </Grid>
                <Grid xs={12} sm={6} item>
                  <TextField
                    label="Nom de famille"
                    placeholder="Entrez votre nom de famille"
                    variant="outlined"
                    fullWidth
                  />
                </Grid>
                <Grid xs={12} item>
                  <TextField
                    type="email"
                    label="Email"
                    placeholder="Entrez votre email"
                    variant="outlined"
                    fullWidth
                    required
                  />
                </Grid>
                <Grid xs={12} item>
                  <TextField
                    type="number"
                    label="Phone"
                    placeholder="Entrez votre numéro de téléphone"
                    variant="outlined"
                    fullWidth
                    required
                  />
                </Grid>
                <Grid xs={12} item>
                  <TextField
                    label="Message"
                    multiline
                    rows={4}
                    placeholder="Entrez votre message"
                    variant="outlined"
                    fullWidth
                    required
                  />
                </Grid>
                <Grid xs={12} item>
                  <Button type="submit" variant="contained" color="primary" fullWidth>
                    Envoyer
                  </Button>
                </Grid>
              </Grid>
            </form>
          </CardContent>
        </Card>
      </main>
      <Footer />
    </div>
  )
}
