import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import { Header } from '../components/header'
import { Footer } from '../components/footer'
import React, { useState } from 'react'
import { Box, Button, TextField, Typography } from '@mui/material'
import LoginOutlinedIcon from '@mui/icons-material/LoginOutlined'
import HowToRegOutlinedIcon from '@mui/icons-material/HowToRegOutlined'
import { loginContact, submitContact } from '../services/users/usersServices'

export const Login = () => {
  const [isSignup, setIsSignup] = useState(false)
  const [inputs, setInputs] = useState({
    firstname: '',
    lastname: '',
    email: '',
    password: ''
  })
  const handleChange = (e: { target: { name: any; value: any } }) => {
    setInputs((prevState) => ({
      ...prevState,
      [e.target.name]: e.target.value
    }))
  }
  const resetState = () => {
    setIsSignup(!isSignup)
    setInputs({ firstname: '', lastname: '', email: '', password: '' })
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <form onSubmit={isSignup ? submitContact : loginContact}>
        <Box
          className="login"
          display="flex"
          flexDirection={'column'}
          maxWidth={400}
          alignItems="center"
          justifyContent={'center'}
          margin="auto"
          marginTop={8}
          padding={5}
          borderRadius={5}
          boxShadow={'5px 5px 10px #ccc'}
          sx={{
            ':hover': {
              boxShadow: '10px 10px 20px #ccc'
            }
          }}
        >
          <Typography variant="h2" padding={3} textAlign="center">
            {isSignup ? 'Signup' : 'Login'}
          </Typography>
          {isSignup && (
            <TextField
              onChange={handleChange}
              name="firstname"
              value={inputs.firstname}
              margin="normal"
              type="text"
              label="Premier nom"
              variant="outlined"
              placeholder="Entrez votre premier nom"
              required
            />
          )}
          {isSignup && (
            <TextField
              onChange={handleChange}
              name="lastname"
              value={inputs.lastname}
              margin="normal"
              type="text"
              label="Deuxième nom"
              variant="outlined"
              placeholder="Entrez votre dernier nom"
              required
            />
          )}
          <TextField
            onChange={handleChange}
            name="email"
            value={inputs.email}
            margin="normal"
            type="email"
            label="Email"
            variant="outlined"
            placeholder="Entrez votre email"
            required
          />
          <TextField
            onChange={handleChange}
            name="password"
            value={inputs.password}
            margin="normal"
            type="password"
            label="Mot de passe"
            variant="outlined"
            placeholder="Entrez votre mot de passe"
            required
          />
          <Button
            endIcon={isSignup ? <HowToRegOutlinedIcon /> : <LoginOutlinedIcon />}
            type="submit"
            sx={{ marginTop: 3, borderRadius: 3 }}
            variant="contained"
            color="info"
          >
            {isSignup ? 'Inscription' : 'Connexion'}
          </Button>
          <Button
            endIcon={isSignup ? <LoginOutlinedIcon /> : <HowToRegOutlinedIcon />}
            onClick={resetState}
            sx={{ marginTop: 3, borderRadius: 3 }}
          >
            {isSignup ? 'Connexion' : 'Inscription'}
          </Button>
        </Box>
      </form>
      <Footer />
    </div>
  )
}

export default Login
