import styles from '../../styles/Home.module.css'
import Head from 'next/head'
import { Header } from '../components/header'
import { Footer } from '../components/footer'

export default function Policy() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus quisquam cumque recusandae a nesciunt expedita
        similique non quis, at labore reiciendis alias aperiam, asperiores qui reprehenderit deserunt vero iste ipsum?
        Facilis nemo dolorum deleniti rem, voluptate velit delectus architecto libero fugiat saepe magni eligendi
        laborum cupiditate sed. At ut accusantium perspiciatis maxime debitis amet ipsum quisquam corrupti quo, placeat
        neque repudiandae commodi et consectetur molestias ducimus expedita porro veritatis temporibus reiciendis harum
        eligendi obcaecati. Soluta nostrum eius, quam dolor dolores tenetur commodi impedit pariatur, itaque maxime
        reiciendis ad eveniet delectus numquam quia fugiat non repudiandae repellendus excepturi suscipit. Cum ratione
        minus deserunt soluta quos quidem cupiditate in aspernatur quas. Iste ipsum qui tenetur porro repellat modi,
        maiores obcaecati iusto molestiae. Ducimus maxime eveniet hic. Culpa ex quasi eos at fugiat minus error vel
        esse? Tempora aperiam quaerat perferendis harum, ab eligendi deleniti velit pariatur optio reiciendis, esse
        dignissimos aut repudiandae. Nemo, vero accusantium? Aliquid illum sed quam nobis iusto. Nulla dolores quisquam
        dolorem, quam asperiores odit facilis numquam, est distinctio ea hic culpa, tempora ex dolorum illum a placeat
        perferendis aspernatur corrupti sed autem! Nostrum architecto voluptas beatae expedita, tempore voluptatem
        aliquid fugit porro consequatur impedit aut repudiandae obcaecati alias minima repellendus optio accusantium
        quos sunt adipisci. Laborum soluta quia ex, assumenda magni atque. Qui aperiam hic totam magni distinctio
        reiciendis non illum voluptatum. Eos a nemo esse iure fuga consequatur architecto atque expedita, beatae placeat
        veniam! Culpa reprehenderit ad corporis ratione impedit! Error alias ea ex vero placeat reprehenderit veniam
        rerum deleniti, quia eum officiis doloremque, voluptatibus dignissimos voluptas aperiam, fugit nihil laboriosam
        quod ullam distinctio quo ut. Beatae ratione, necessitatibus, sed error impedit perspiciatis perferendis ea
        inventore ducimus cupiditate maxime! Ullam eaque dicta soluta asperiores quam enim rerum, nisi iure quidem ad
        atque veritatis, laudantium qui neque. Explicabo sit earum ea dicta deserunt quisquam soluta, unde iure eius
        inventore. In magnam ex asperiores iste iure sunt necessitatibus sed voluptatum sapiente expedita provident
        commodi ab magni non saepe corrupti id neque error quas mollitia molestiae temporibus, omnis inventore. Ab, nemo
        ut expedita dolores eos, aliquam laudantium illum, odio omnis quod velit iste! Ducimus libero aperiam eum, at ea
        nulla. Explicabo assumenda commodi velit laboriosam ullam tempora placeat? Labore, odit. Fugit, ipsum sit nihil
        incidunt mollitia quod. Nous allons vendre vos données. Omnis suscipit, voluptas fuga alias, ea labore nisi
        nostrum quaerat officia expedita ipsum distinctio sint tempore porro itaque ratione rerum minima veritatis
        praesentium enim laudantium? Obcaecati alias neque impedit est iure vitae illum, temporibus, hic libero cum
        totam dignissimos deleniti possimus blanditiis provident voluptatibus labore non similique sed minima assumenda
        vero quisquam fuga sapiente. Aliquam ullam dolores dolore enim quos maxime? Quis dolor autem iusto labore
        voluptates possimus velit! Maxime impedit ad, ipsa numquam a minima corrupti totam nobis, doloremque, commodi
        inventore sequi optio atque repellat fuga dolorem dolores possimus iste earum eveniet minus tenetur. Et vos
        organes aussi. Eius facere fugiat asperiores vel. Ad aliquam necessitatibus optio nulla unde, voluptate maiores
        deserunt consequuntur voluptatum, quibusdam animi! Praesentium nesciunt vero aut eius! Qui officiis tempora
        omnis tempore ex facere ut. Cupiditate voluptas voluptates soluta maxime dolorum ad veritatis, doloremque
        dolores voluptate amet explicabo, iste corporis consectetur unde, sapiente consequuntur sint dicta quibusdam
        temporibus beatae nostrum illum voluptatibus sunt. Eos quod, ipsum dignissimos corporis doloribus, iusto
        possimus est numquam molestias ab in modi, nesciunt consequatur pariatur quaerat ea quia! Voluptas vel illum
        facilis suscipit optio doloribus obcaecati nesciunt sunt eligendi. Voluptatum, iusto? Veritatis repudiandae aut,
        eaque explicabo, porro doloremque voluptate sed sunt quae possimus, nihil id libero culpa officia odit! Magni
        doloribus natus, recusandae qui at culpa officia tenetur totam nam architecto repellendus maxime porro quasi
        labore dignissimos ipsa deserunt! Iusto ad molestiae dicta ea provident quod maiores minus, repellendus mollitia
        aliquam cum voluptatibus commodi ducimus facilis distinctio, cumque consequatur doloremque, aperiam sequi
        quisquam natus! Enim ex natus ipsum modi iure error nam ea perferendis nostrum deleniti? Incidunt maiores veniam
        nulla, harum facere cum consequatur quisquam? Ex veniam distinctio expedita maiores error voluptatibus ipsam
        quas, vel ab quam officiis laborum earum reiciendis repellendus quidem atque velit tempore at harum esse eum
        laboriosam in vero facilis! Minima ratione quaerat corrupti architecto illum nulla ea fuga dolorem mollitia
        ipsum nostrum officiis nobis labore, ducimus nihil delectus omnis quo quod consequuntur possimus corporis dolor.
        Perferendis est accusantium autem amet eum officia iusto sit illo repellendus. Reprehenderit non cumque atque
        beatae accusantium ex laboriosam dolorum, sint consequatur voluptatum nihil laudantium esse ratione, dolores
        dolore aliquam asperiores repellat eos rem eum! Voluptatum hic vero quae eos velit veritatis impedit veniam
        animi ipsam porro pariatur corrupti, id voluptatem aspernatur reprehenderit praesentium, officia sapiente
        laboriosam vitae expedita. Mollitia deleniti saepe distinctio quis autem. Optio eveniet, autem modi culpa qui
        quia pariatur, maxime vero possimus ratione eligendi harum aut architecto quisquam quod in. Eveniet eligendi
        facere minima eaque maiores quibusdam minus quia eius obcaecati, dolor, voluptatum ratione nostrum expedita
        ipsam ab in architecto ullam, repellat tempore consequuntur quos unde iure id. Ut blanditiis fuga quasi,
        excepturi voluptates dolore mollitia, tempora sapiente numquam quaerat vero animi, nihil neque aliquam minima
        maxime et illum facilis? Numquam quibusdam repudiandae excepturi, iusto ipsa recusandae ducimus laboriosam
        veniam quia ullam commodi esse nostrum! Sunt, nihil pariatur ex hic qui obcaecati a temporibus quos non placeat
        eaque corrupti, dignissimos esse porro id sit asperiores! Ex architecto veniam hic aperiam labore explicabo
        dolorum dolores nam. Totam, aliquid? Sit illo unde tenetur ipsam blanditiis quo expedita! A porro minima
        nesciunt explicabo officia quo quibusdam mollitia delectus non beatae atque eos, natus rem exercitationem,
        itaque maiores harum ad odio ipsam sequi temporibus ipsa voluptate. Corporis assumenda expedita saepe eaque
        fuga, commodi ex at repellat temporibus, ullam modi est explicabo. Dignissimos beatae accusamus nam modi commodi
        doloremque fuga quibusdam est libero culpa illo, doloribus quae exercitationem, laudantium, fugiat cum tempora
        vel! Sequi, eaque! Magni sunt eaque optio tenetur quasi error! Necessitatibus iste libero molestias harum
        voluptatibus, nam dolor itaque labore quasi dicta quisquam ducimus, rem reiciendis veniam sed exercitationem
        quos error qui consequatur. Aspernatur minima, facilis assumenda sint quis dolores accusantium tempora rem minus
        quae asperiores a dolorum inventore doloribus voluptas enim possimus, unde voluptatum, dolor maxime quas. Quia
        asperiores culpa incidunt ducimus beatae, architecto laborum, voluptate error aliquam, dolorem veritatis. Id
        fuga assumenda a maiores veritatis. Ipsum corporis quaerat inventore possimus. Est excepturi dignissimos
        deserunt maxime numquam, ducimus consequatur quas eligendi, ipsam quos exercitationem harum aliquid, animi
        adipisci aspernatur illo tenetur ea. Quae, est dolore optio quo corrupti, perspiciatis rem id atque reiciendis
        soluta natus. Amet magnam perspiciatis deleniti iure ullam maiores adipisci, autem, sed inventore tempore in?
        Incidunt sint dolorum sapiente quis eum natus error omnis consequuntur quasi, quibusdam accusantium doloremque
        esse alias id a laudantium quod, impedit at. Inventore maiores perspiciatis vero debitis repellendus, eius
        reiciendis corporis cupiditate culpa beatae delectus harum cum enim necessitatibus adipisci, in optio officiis
        mollitia sit porro dignissimos pariatur? Reprehenderit quos ea at porro laborum iusto neque ab possimus
        accusantium, a, rem officia adipisci, pariatur exercitationem sunt obcaecati eos. Voluptatibus eius doloremque
        asperiores nulla distinctio! Corrupti, expedita vero! Nemo optio atque impedit voluptates iure, laborum
        voluptatum modi sunt et dolorum doloribus dignissimos nulla quas nobis. Quos eos aliquam exercitationem ut
        inventore! Voluptatum quos id ut tempora odio natus error impedit, dolor, sequi corporis aliquid blanditiis
        nulla ea esse, autem sint nemo iure necessitatibus aperiam modi illo repudiandae molestias dolores doloribus.
        Ipsum blanditiis quidem tempore atque minima asperiores placeat ut culpa, architecto molestias, molestiae
        laudantium nisi porro deserunt ad? Deserunt dolore harum sunt consectetur ullam maiores quia tenetur reiciendis
        sapiente hic beatae temporibus tempora nesciunt veritatis dignissimos eveniet esse ex minima ducimus soluta
        quisquam, consequatur quis ab! Inventore officia nemo, quis laboriosam, hic ea veniam quae iste vel iusto dicta?
        Ducimus mollitia quisquam eos temporibus saepe aliquam sint asperiores commodi qui nesciunt quod sit, deleniti
        id tempora vitae ipsam fugiat aspernatur ex modi itaque ab unde porro. Exercitationem quasi rerum in dignissimos
        nesciunt reiciendis velit earum accusantium quaerat, esse, voluptate mollitia nam? Sunt beatae dolorum ab
        aliquid quam excepturi aspernatur sapiente fugit autem id doloribus veniam quaerat commodi, veritatis,
        temporibus pariatur repellat possimus voluptatibus inventore sed iusto eaque odit similique facilis? At sapiente
        velit vitae in id aliquid, ad recusandae nihil amet quasi sit asperiores sequi earum maxime quia voluptas
        repellat? Ut quae ratione tenetur non facilis consequuntur suscipit deleniti ducimus impedit, omnis eaque
        dignissimos accusantium sapiente neque nesciunt quis nemo voluptate vitae! Laudantium sapiente aliquam saepe.
        Atque ab repellat error inventore dicta ducimus expedita pariatur vero! Blanditiis eum quia repudiandae corporis
        nobis illo id laborum quasi possimus, consequuntur esse cumque distinctio magnam in fuga eaque explicabo
        voluptatum quidem. Quasi repudiandae quaerat accusamus aliquid nisi. Officia minima quasi debitis doloribus
        delectus suscipit non ab ducimus sapiente, tenetur accusamus distinctio in quis vero ad deleniti quo temporibus
        quidem? Mollitia molestiae atque consequuntur aliquam saepe nam excepturi eius deserunt laborum quibusdam quia
        facilis, totam temporibus blanditiis repellendus quos dicta natus nostrum et voluptatem quaerat labore unde
        alias tenetur? Molestias, molestiae suscipit! Tenetur aspernatur, expedita delectus quam odit perferendis
        cupiditate ducimus ad amet doloremque! Velit distinctio quidem non consequatur totam? Eos alias perferendis
        voluptate laborum sit aliquid iure ab nihil nemo praesentium. Ex in tempore ipsa magnam saepe a quo quia,
        consectetur similique enim sapiente vero aperiam tempora exercitationem optio repellat. Explicabo maiores
        eligendi omnis blanditiis perferendis perspiciatis quos quibusdam cumque ab tenetur corporis voluptate sit
        repellendus delectus odio, veniam provident quae ullam a cupiditate doloribus corrupti iure error quaerat?
        Dolore accusantium voluptate eveniet saepe nam quibusdam laboriosam atque distinctio deleniti quasi blanditiis
        odit laborum facilis, eum et veniam quidem nisi. Natus, velit, magni laudantium vitae accusamus libero iure
        ipsum sunt cum, possimus dolore? Eveniet repudiandae minima est officia natus debitis, illo totam aperiam
        reiciendis illum quia voluptate officiis similique delectus perferendis corporis fugiat facilis ducimus alias
        atque excepturi in, sunt nisi? Incidunt veniam asperiores vero, quaerat eum perspiciatis delectus quasi illum
        quisquam, nostrum sed iure impedit laudantium optio expedita unde. Assumenda ea earum dolore at, commodi
        necessitatibus quas perspiciatis consequuntur officia nihil incidunt eos expedita aliquam! Laborum, perferendis.
        Libero quos optio est ullam dicta, hic in iste explicabo deserunt dolore dolores delectus earum cum soluta ipsam
        accusantium possimus voluptas voluptates dignissimos recusandae minus ut beatae praesentium labore. Perferendis
        doloremque itaque laudantium. Expedita libero molestias earum! Explicabo voluptate voluptatem assumenda minima
        hic dolorum eveniet aperiam dolore maxime! Suscipit culpa labore quis, reprehenderit deleniti amet, fuga
        architecto, assumenda fugiat porro nesciunt explicabo eaque adipisci animi iusto. Officiis, iste animi? Earum
        iste doloremque odit aperiam deserunt at esse quis nemo, nobis cum quae. Placeat qui quia, quas perspiciatis,
        ullam laudantium esse, impedit non saepe nobis nulla consectetur deserunt odit. Eum voluptate explicabo,
        sapiente cumque, nihil placeat nemo quisquam repellat at cum sit enim nam minima nostrum harum tenetur, corporis
        molestiae? Voluptate sit autem dolores laudantium sed consectetur doloribus asperiores, repudiandae inventore
        id, vitae vero ab error consequatur ipsum soluta beatae fugiat itaque. Cum, repellendus fugiat asperiores ut at
        laudantium velit temporibus eligendi. Cupiditate enim amet odio eligendi quibusdam eum quaerat sunt adipisci
        facere? Voluptatum odit officiis in nesciunt, suscipit nulla molestiae eius harum consectetur. Modi aliquid
        similique veniam blanditiis fuga? Numquam exercitationem labore delectus at esse doloremque debitis nobis maxime
        ut architecto beatae adipisci soluta non, accusamus distinctio, quod amet quidem doloribus excepturi suscipit
        corrupti. Debitis quibusdam voluptatibus consectetur fugit maxime obcaecati quam? Placeat magnam alias
        dignissimos sunt dolore molestiae inventore iusto voluptatem, nobis assumenda dolor porro debitis, autem minima
        odio harum ea nostrum consequatur sint doloremque in asperiores, exercitationem mollitia veniam. Consequatur
        vero error tenetur officiis, ea placeat deserunt non, eveniet illo eum mollitia exercitationem quae tempora
        necessitatibus officia iusto minima. Minima, error qui. Veniam quam quia tempore fugiat necessitatibus
        voluptatem, earum quas nisi ducimus expedita ipsa officia cum architecto. Doloremque alias necessitatibus
        explicabo sit rem itaque quisquam odio illo, ex autem dolorum magnam accusantium magni. Fugit voluptate expedita
        facilis odio tempora excepturi aperiam? Tempore atque autem praesentium laboriosam eum quaerat suscipit
        consequatur nihil eius recusandae! Dolores pariatur ratione modi eveniet omnis deleniti saepe ut ex distinctio
        obcaecati expedita voluptate cumque, repudiandae ullam facere nulla quos perspiciatis? Esse repellat voluptatem
        aspernatur beatae vitae. 🔪 🩸
      </p>
      <Footer />
    </div>
  )
}
